version: '3'
services:      
  web_scraper_db:
    image: mysql:latest
    container_name: web_scraper_db
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER="${MYSQL_USER}"
    command: '--default-authentication-plugin=mysql_native_password'